site_name: ''

extra_css:
  - css/custom.css

theme:
  name: mkdocs
  language: zh
  features:
    - navigation.tabs          # ⭐ 顶部横向导航栏
    - navigation.tabs.sticky   # ⭐ 固定顶部导航
    - navigation.instant
    - content.code.copy
    - toc.integrate

nav:
  - Home: index.md
  - About: '#about'
  - Call for Papers: '#call-for-papers'
  - Important Dates: '#important-dates'
  - Speakers: '#speakers'
  - Organizer: '#organizer'

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences



